version: 2.1

commands:
  install_dependencies:
    steps:
      - checkout
      - restore_cache:
          keys:
            - node_modules-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - node_modules-{{ .Branch }}-
            - node_modules-
      - run:
          name: Install Dependencies
          command: yarn
      - save_cache:
          key: node_modules-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
  format:
    steps:
      - run:
          name: Format with Prettier
          command: yarn format
  build:
    steps:
      - run:
          name: Build
          command: yarn build

executors:
  docker-executor:
    docker:
      - image: 'cimg/node:17.1.0'

jobs:
  format:
    executor: docker-executor
    steps:
      - install_dependencies
      - format
  build:
    executor: docker-executor
    steps:
      - install_dependencies
      - build

workflows:
  pull_request:
    jobs:
      - format
      - build
