name: Prettier

on:
  pull_request:
    branches: [main]

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Prettify code
        uses: creyD/prettier_action@v4.0
        with:
          dry: true
          prettier_options: --write **/*.{ts,tsx,js,jsx,css,sass,html,md,yml}
